import {MigrationInterface, QueryRunner} from "typeorm";

export class AlmostDoneClivy1646956490605 implements MigrationInterface {
    name = 'AlmostDoneClivy1646956490605'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "comment_like" ("user_id" integer NOT NULL, "comment_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_b81e662a725f9440050ac6e4e28" PRIMARY KEY ("user_id", "comment_id"))`);
        await queryRunner.query(`CREATE TABLE "like" ("user_id" integer NOT NULL, "post_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_3221edd468ef18cc93a806b74b2" PRIMARY KEY ("user_id", "post_id"))`);
        await queryRunner.query(`CREATE TABLE "caption_user_tag" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "user_string" character varying NOT NULL, CONSTRAINT "PK_900ddfb9de25103157682cec85b" PRIMARY KEY ("post_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "videogame_user_preferences" ("user_id" integer NOT NULL, "videogame_id" integer NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "viewCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_300d33892a73cb669e7b4980dd1" PRIMARY KEY ("user_id", "videogame_id"))`);
        await queryRunner.query(`CREATE TABLE "videogame" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "file_key" character varying NOT NULL, "tapCount" integer NOT NULL DEFAULT '0', "postCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_a9b00a577b002ce1584b97d192d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "videogame_genre_videogame" ("videogame_genre_id" integer NOT NULL, "videogame_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_ef4849a7acf0dc69f35c90c078b" PRIMARY KEY ("videogame_genre_id", "videogame_id"))`);
        await queryRunner.query(`CREATE TABLE "videogame_genre_user_preferences" ("user_id" integer NOT NULL, "genre_id" integer NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "viewCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_84a43dcfaeeb4dfd697ebfb465d" PRIMARY KEY ("user_id", "genre_id"))`);
        await queryRunner.query(`CREATE TABLE "videogame_genre" ("id" SERIAL NOT NULL, "videogame_genre" character varying NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_2b0b906125b50d37c73399274e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "videogame_genre_post" ("videogame_genre_id" integer NOT NULL, "post_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_32f543dd7ba22b6b5b6f657e379" PRIMARY KEY ("videogame_genre_id", "post_id"))`);
        await queryRunner.query(`CREATE TABLE "post_view" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_a9600c2623204049cea7ee115cf" PRIMARY KEY ("post_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "like_notification" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_b195062a5b770c1ec8aecef0d2" UNIQUE ("post_id", "user_id", "type"), CONSTRAINT "PK_b195062a5b770c1ec8aecef0d25" PRIMARY KEY ("post_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "post" ("id" SERIAL NOT NULL, "caption" character varying NOT NULL, "file_key" character varying NOT NULL, "fileWidth" integer NOT NULL, "fileHeight" integer NOT NULL, "fileGifKey" character varying NOT NULL, "fileImgKey" character varying NOT NULL, "user_id" integer NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "videogame_id" integer, "viewsCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "caption_tag_notification" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_5d75aa58bb1fc6bed264e5f7b9" UNIQUE ("post_id", "user_id", "type"), CONSTRAINT "PK_5d75aa58bb1fc6bed264e5f7b98" PRIMARY KEY ("post_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "comment_notification" ("comment_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_f0672195675dfe991ebf82ea63" UNIQUE ("comment_id", "user_id", "type"), CONSTRAINT "PK_f0672195675dfe991ebf82ea63a" PRIMARY KEY ("comment_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "comment_tag_notification" ("comment_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_00a1b89674b8d7a82dc22f08b3" UNIQUE ("comment_id", "user_id", "type"), CONSTRAINT "PK_00a1b89674b8d7a82dc22f08b37" PRIMARY KEY ("comment_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "follow_notification" ("follower_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_9cd5f20a15086889490f971e90" UNIQUE ("follower_id", "user_id", "type"), CONSTRAINT "PK_9cd5f20a15086889490f971e909" PRIMARY KEY ("follower_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "reply_like" ("user_id" integer NOT NULL, "reply_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_0978c881738e7e45446cb731942" PRIMARY KEY ("user_id", "reply_id"))`);
        await queryRunner.query(`CREATE TABLE "reply_notification" ("reply_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_853624bc4b28dedf5880d4ada3" UNIQUE ("reply_id", "user_id", "type"), CONSTRAINT "PK_853624bc4b28dedf5880d4ada37" PRIMARY KEY ("reply_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "reply_tag_notification" ("reply_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_8b9da585fe61d8316af1220863" UNIQUE ("reply_id", "user_id", "type"), CONSTRAINT "PK_8b9da585fe61d8316af12208630" PRIMARY KEY ("reply_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "reply_user_tag" ("reply_id" integer NOT NULL, "user_id" integer NOT NULL, "user_string" character varying NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_c4dcb183739620119d5551a2e67" PRIMARY KEY ("reply_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "reply" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "comment_id" integer NOT NULL, "reply" character varying NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_94fa9017051b40a71e000a2aff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reply_like_notification" ("reply_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_d9662dcdc2abbce45cfcb17060" UNIQUE ("reply_id", "user_id", "type"), CONSTRAINT "PK_d9662dcdc2abbce45cfcb170603" PRIMARY KEY ("reply_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("parent_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_4a8b1443d60bc87e4ff9ecffe7b" PRIMARY KEY ("parent_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "comment_like_notification" ("comment_id" integer NOT NULL, "user_id" integer NOT NULL, "type" character varying NOT NULL, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "REL_c14091a63b0d6b1431e7be1e91" UNIQUE ("comment_id", "user_id", "type"), CONSTRAINT "PK_c14091a63b0d6b1431e7be1e914" PRIMARY KEY ("comment_id", "user_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "comment_user_tag" ("comment_id" integer NOT NULL, "user_id" integer NOT NULL, "user_string" character varying NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_46e8076e3a7441f0ed4487d3c77" PRIMARY KEY ("comment_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "post_id" integer NOT NULL, "comment" character varying NOT NULL, "replyCount" integer NOT NULL DEFAULT '0', "likeCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_search" ("userId" integer NOT NULL, "searchedUserId" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_69c621ef3a60e2603484a0bb531" PRIMARY KEY ("userId", "searchedUserId"))`);
        await queryRunner.query(`CREATE TABLE "follow" ("followerId" integer NOT NULL, "followingId" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_2952595a5bec0052c5da0751cca" PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`CREATE TABLE "device_token" ("token" character varying NOT NULL, "platform" character varying NOT NULL, "user_id" integer NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_0c2fea70782201aba345e971fe3" PRIMARY KEY ("token", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "bio" character varying NOT NULL DEFAULT '', "file_key" character varying NOT NULL, "small_file_key" character varying NOT NULL, "password" character varying NOT NULL, "postCount" integer NOT NULL DEFAULT '0', "followersCount" integer NOT NULL DEFAULT '0', "followingCount" integer NOT NULL DEFAULT '0', "birthday" date NOT NULL, "createdAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "comment_like" ADD CONSTRAINT "FK_fd7207639a77fa0f1fea8943b78" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_like" ADD CONSTRAINT "FK_4a0c128374ff87d4641cab920f0" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_4356ac2f9519c7404a2869f1691" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_d41caa70371e578e2a4791a88ae" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caption_user_tag" ADD CONSTRAINT "FK_d44e80026ebdf331e782a06c2b8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caption_user_tag" ADD CONSTRAINT "FK_c96718f48b90041a65d6f6d6e1e" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_user_preferences" ADD CONSTRAINT "FK_55c439b22a063156968e9755e74" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_user_preferences" ADD CONSTRAINT "FK_8461d1d7c83ada490a57bbfe776" FOREIGN KEY ("videogame_id") REFERENCES "videogame"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_videogame" ADD CONSTRAINT "FK_63076afd6fedfacbe0e6f6330b6" FOREIGN KEY ("videogame_genre_id") REFERENCES "videogame_genre"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_videogame" ADD CONSTRAINT "FK_b676308e0deaefcc8f9fabe6424" FOREIGN KEY ("videogame_id") REFERENCES "videogame"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_user_preferences" ADD CONSTRAINT "FK_811a0af7dd87c16088699b1c172" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_user_preferences" ADD CONSTRAINT "FK_bd8454ece8e337e4788acd969ec" FOREIGN KEY ("genre_id") REFERENCES "videogame_genre"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_post" ADD CONSTRAINT "FK_71cf150363b1ba0cfad6370feba" FOREIGN KEY ("videogame_genre_id") REFERENCES "videogame_genre"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_post" ADD CONSTRAINT "FK_b1413abbabb388961761ac4e7db" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_view" ADD CONSTRAINT "FK_72c52f1354467735fb51efef486" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_view" ADD CONSTRAINT "FK_74891cf0e56d9f942c8d55babd0" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like_notification" ADD CONSTRAINT "FK_b195062a5b770c1ec8aecef0d25" FOREIGN KEY ("post_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like_notification" ADD CONSTRAINT "FK_4d341fe3f4c540aa86bbabc652c" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like_notification" ADD CONSTRAINT "FK_cd850eb14e4ac2d4111597677e1" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_52378a74ae3724bcab44036645b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_59a49f7ee9da0559fc3edac6fb0" FOREIGN KEY ("videogame_id") REFERENCES "videogame"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" ADD CONSTRAINT "FK_5d75aa58bb1fc6bed264e5f7b98" FOREIGN KEY ("post_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" ADD CONSTRAINT "FK_2e9a102da09fc1b4ddffff54c3f" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" ADD CONSTRAINT "FK_8a220e7c08c4a865a4d97f1d86b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_notification" ADD CONSTRAINT "FK_f0672195675dfe991ebf82ea63a" FOREIGN KEY ("comment_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_notification" ADD CONSTRAINT "FK_d68d6465c9a63edb2f3212b506a" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_notification" ADD CONSTRAINT "FK_4129d258ad6da8387545025aebd" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" ADD CONSTRAINT "FK_00a1b89674b8d7a82dc22f08b37" FOREIGN KEY ("comment_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" ADD CONSTRAINT "FK_7ee5773e2b21d8bb7e2d8090c8b" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" ADD CONSTRAINT "FK_4a6f80b62928733291368bbd16d" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow_notification" ADD CONSTRAINT "FK_9cd5f20a15086889490f971e909" FOREIGN KEY ("follower_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow_notification" ADD CONSTRAINT "FK_91ce08f1bd5d73ff380abefdf4f" FOREIGN KEY ("follower_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow_notification" ADD CONSTRAINT "FK_e8a619928caba8e4d9e5462f191" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like" ADD CONSTRAINT "FK_50020700e6334e849ad0403baba" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like" ADD CONSTRAINT "FK_20d2d1b4f5bc22975f452e2d37d" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_notification" ADD CONSTRAINT "FK_853624bc4b28dedf5880d4ada37" FOREIGN KEY ("reply_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_notification" ADD CONSTRAINT "FK_6c988788c4a427de19b191d5e54" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_notification" ADD CONSTRAINT "FK_f5ab5c7889c623222ddbdb9e5b2" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" ADD CONSTRAINT "FK_8b9da585fe61d8316af12208630" FOREIGN KEY ("reply_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" ADD CONSTRAINT "FK_04b9b8e56f3ec34c0faf4b41954" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" ADD CONSTRAINT "FK_c04555aa4df09b98c980e50ac50" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_user_tag" ADD CONSTRAINT "FK_8cf9c0c16c23e9e3162b8370ffe" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_user_tag" ADD CONSTRAINT "FK_96a46770065c3c164f5ae718767" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_ff320a60506a27ed687ed8e99b9" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_aa280a5b48fd06db0868a6fa4e1" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" ADD CONSTRAINT "FK_d9662dcdc2abbce45cfcb170603" FOREIGN KEY ("reply_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" ADD CONSTRAINT "FK_d80879873a11bc0f30f47292b47" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" ADD CONSTRAINT "FK_5d24db16952d384774f97cf2432" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" ADD CONSTRAINT "FK_c14091a63b0d6b1431e7be1e914" FOREIGN KEY ("comment_id", "user_id", "type") REFERENCES "notification"("parent_id","user_id","type") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" ADD CONSTRAINT "FK_501195cc9443a1f32a2c4b50e8f" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" ADD CONSTRAINT "FK_ae156bc9d6da5d4969e0c38219b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_user_tag" ADD CONSTRAINT "FK_586caeefd011eb2b6df75b762bd" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_user_tag" ADD CONSTRAINT "FK_bf3168f82c1fa83a4f74d665530" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_8aa21186314ce53c5b61a0e8c93" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_search" ADD CONSTRAINT "FK_cfd858fb013b4a2deb6a1e30cc0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_search" ADD CONSTRAINT "FK_8d91888cbe60bd937d36b6ae77f" FOREIGN KEY ("searchedUserId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow" ADD CONSTRAINT "FK_550dce89df9570f251b6af2665a" FOREIGN KEY ("followerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow" ADD CONSTRAINT "FK_e9f68503556c5d72a161ce38513" FOREIGN KEY ("followingId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_token" ADD CONSTRAINT "FK_aca74edfcfd458e0cb313e9d099" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "device_token" DROP CONSTRAINT "FK_aca74edfcfd458e0cb313e9d099"`);
        await queryRunner.query(`ALTER TABLE "follow" DROP CONSTRAINT "FK_e9f68503556c5d72a161ce38513"`);
        await queryRunner.query(`ALTER TABLE "follow" DROP CONSTRAINT "FK_550dce89df9570f251b6af2665a"`);
        await queryRunner.query(`ALTER TABLE "user_search" DROP CONSTRAINT "FK_8d91888cbe60bd937d36b6ae77f"`);
        await queryRunner.query(`ALTER TABLE "user_search" DROP CONSTRAINT "FK_cfd858fb013b4a2deb6a1e30cc0"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_8aa21186314ce53c5b61a0e8c93"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7"`);
        await queryRunner.query(`ALTER TABLE "comment_user_tag" DROP CONSTRAINT "FK_bf3168f82c1fa83a4f74d665530"`);
        await queryRunner.query(`ALTER TABLE "comment_user_tag" DROP CONSTRAINT "FK_586caeefd011eb2b6df75b762bd"`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" DROP CONSTRAINT "FK_ae156bc9d6da5d4969e0c38219b"`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" DROP CONSTRAINT "FK_501195cc9443a1f32a2c4b50e8f"`);
        await queryRunner.query(`ALTER TABLE "comment_like_notification" DROP CONSTRAINT "FK_c14091a63b0d6b1431e7be1e914"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" DROP CONSTRAINT "FK_5d24db16952d384774f97cf2432"`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" DROP CONSTRAINT "FK_d80879873a11bc0f30f47292b47"`);
        await queryRunner.query(`ALTER TABLE "reply_like_notification" DROP CONSTRAINT "FK_d9662dcdc2abbce45cfcb170603"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_aa280a5b48fd06db0868a6fa4e1"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_ff320a60506a27ed687ed8e99b9"`);
        await queryRunner.query(`ALTER TABLE "reply_user_tag" DROP CONSTRAINT "FK_96a46770065c3c164f5ae718767"`);
        await queryRunner.query(`ALTER TABLE "reply_user_tag" DROP CONSTRAINT "FK_8cf9c0c16c23e9e3162b8370ffe"`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" DROP CONSTRAINT "FK_c04555aa4df09b98c980e50ac50"`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" DROP CONSTRAINT "FK_04b9b8e56f3ec34c0faf4b41954"`);
        await queryRunner.query(`ALTER TABLE "reply_tag_notification" DROP CONSTRAINT "FK_8b9da585fe61d8316af12208630"`);
        await queryRunner.query(`ALTER TABLE "reply_notification" DROP CONSTRAINT "FK_f5ab5c7889c623222ddbdb9e5b2"`);
        await queryRunner.query(`ALTER TABLE "reply_notification" DROP CONSTRAINT "FK_6c988788c4a427de19b191d5e54"`);
        await queryRunner.query(`ALTER TABLE "reply_notification" DROP CONSTRAINT "FK_853624bc4b28dedf5880d4ada37"`);
        await queryRunner.query(`ALTER TABLE "reply_like" DROP CONSTRAINT "FK_20d2d1b4f5bc22975f452e2d37d"`);
        await queryRunner.query(`ALTER TABLE "reply_like" DROP CONSTRAINT "FK_50020700e6334e849ad0403baba"`);
        await queryRunner.query(`ALTER TABLE "follow_notification" DROP CONSTRAINT "FK_e8a619928caba8e4d9e5462f191"`);
        await queryRunner.query(`ALTER TABLE "follow_notification" DROP CONSTRAINT "FK_91ce08f1bd5d73ff380abefdf4f"`);
        await queryRunner.query(`ALTER TABLE "follow_notification" DROP CONSTRAINT "FK_9cd5f20a15086889490f971e909"`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" DROP CONSTRAINT "FK_4a6f80b62928733291368bbd16d"`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" DROP CONSTRAINT "FK_7ee5773e2b21d8bb7e2d8090c8b"`);
        await queryRunner.query(`ALTER TABLE "comment_tag_notification" DROP CONSTRAINT "FK_00a1b89674b8d7a82dc22f08b37"`);
        await queryRunner.query(`ALTER TABLE "comment_notification" DROP CONSTRAINT "FK_4129d258ad6da8387545025aebd"`);
        await queryRunner.query(`ALTER TABLE "comment_notification" DROP CONSTRAINT "FK_d68d6465c9a63edb2f3212b506a"`);
        await queryRunner.query(`ALTER TABLE "comment_notification" DROP CONSTRAINT "FK_f0672195675dfe991ebf82ea63a"`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" DROP CONSTRAINT "FK_8a220e7c08c4a865a4d97f1d86b"`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" DROP CONSTRAINT "FK_2e9a102da09fc1b4ddffff54c3f"`);
        await queryRunner.query(`ALTER TABLE "caption_tag_notification" DROP CONSTRAINT "FK_5d75aa58bb1fc6bed264e5f7b98"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_59a49f7ee9da0559fc3edac6fb0"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_52378a74ae3724bcab44036645b"`);
        await queryRunner.query(`ALTER TABLE "like_notification" DROP CONSTRAINT "FK_cd850eb14e4ac2d4111597677e1"`);
        await queryRunner.query(`ALTER TABLE "like_notification" DROP CONSTRAINT "FK_4d341fe3f4c540aa86bbabc652c"`);
        await queryRunner.query(`ALTER TABLE "like_notification" DROP CONSTRAINT "FK_b195062a5b770c1ec8aecef0d25"`);
        await queryRunner.query(`ALTER TABLE "post_view" DROP CONSTRAINT "FK_74891cf0e56d9f942c8d55babd0"`);
        await queryRunner.query(`ALTER TABLE "post_view" DROP CONSTRAINT "FK_72c52f1354467735fb51efef486"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_post" DROP CONSTRAINT "FK_b1413abbabb388961761ac4e7db"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_post" DROP CONSTRAINT "FK_71cf150363b1ba0cfad6370feba"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_user_preferences" DROP CONSTRAINT "FK_bd8454ece8e337e4788acd969ec"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_user_preferences" DROP CONSTRAINT "FK_811a0af7dd87c16088699b1c172"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_videogame" DROP CONSTRAINT "FK_b676308e0deaefcc8f9fabe6424"`);
        await queryRunner.query(`ALTER TABLE "videogame_genre_videogame" DROP CONSTRAINT "FK_63076afd6fedfacbe0e6f6330b6"`);
        await queryRunner.query(`ALTER TABLE "videogame_user_preferences" DROP CONSTRAINT "FK_8461d1d7c83ada490a57bbfe776"`);
        await queryRunner.query(`ALTER TABLE "videogame_user_preferences" DROP CONSTRAINT "FK_55c439b22a063156968e9755e74"`);
        await queryRunner.query(`ALTER TABLE "caption_user_tag" DROP CONSTRAINT "FK_c96718f48b90041a65d6f6d6e1e"`);
        await queryRunner.query(`ALTER TABLE "caption_user_tag" DROP CONSTRAINT "FK_d44e80026ebdf331e782a06c2b8"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_d41caa70371e578e2a4791a88ae"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_4356ac2f9519c7404a2869f1691"`);
        await queryRunner.query(`ALTER TABLE "comment_like" DROP CONSTRAINT "FK_4a0c128374ff87d4641cab920f0"`);
        await queryRunner.query(`ALTER TABLE "comment_like" DROP CONSTRAINT "FK_fd7207639a77fa0f1fea8943b78"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "device_token"`);
        await queryRunner.query(`DROP TABLE "follow"`);
        await queryRunner.query(`DROP TABLE "user_search"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "comment_user_tag"`);
        await queryRunner.query(`DROP TABLE "comment_like_notification"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "reply_like_notification"`);
        await queryRunner.query(`DROP TABLE "reply"`);
        await queryRunner.query(`DROP TABLE "reply_user_tag"`);
        await queryRunner.query(`DROP TABLE "reply_tag_notification"`);
        await queryRunner.query(`DROP TABLE "reply_notification"`);
        await queryRunner.query(`DROP TABLE "reply_like"`);
        await queryRunner.query(`DROP TABLE "follow_notification"`);
        await queryRunner.query(`DROP TABLE "comment_tag_notification"`);
        await queryRunner.query(`DROP TABLE "comment_notification"`);
        await queryRunner.query(`DROP TABLE "caption_tag_notification"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TABLE "like_notification"`);
        await queryRunner.query(`DROP TABLE "post_view"`);
        await queryRunner.query(`DROP TABLE "videogame_genre_post"`);
        await queryRunner.query(`DROP TABLE "videogame_genre"`);
        await queryRunner.query(`DROP TABLE "videogame_genre_user_preferences"`);
        await queryRunner.query(`DROP TABLE "videogame_genre_videogame"`);
        await queryRunner.query(`DROP TABLE "videogame"`);
        await queryRunner.query(`DROP TABLE "videogame_user_preferences"`);
        await queryRunner.query(`DROP TABLE "caption_user_tag"`);
        await queryRunner.query(`DROP TABLE "like"`);
        await queryRunner.query(`DROP TABLE "comment_like"`);
    }

}
