// videogames with name and img

// 

export enum VideogameGenres {
  Action = 'Action',
  Adventure = 'Adventure',
  Arcade = 'Arcade',
  Fighting = 'Fighting',
  Sports = 'Sports',
  FPS = 'FPS',
  Strategy = 'Strategy',
  Multiplayer = 'Multiplayer',
  SinglePlayer = 'Single Player',
  SingleAndMultiplayer = 'Single & Multiplayer',
  Racing = 'Racing',
  Puzzles = 'Puzzles',
  Simulation = 'Simulation',
  OpenWorld = 'Open World',
  MMO = 'MMO',
  Stealth = 'Stealth',
  Gambling = 'Gambling',
  Horror = 'Horror',
  Survival = 'Survival',
  MOBA = 'MOBA',
  RTS = 'RTS',
  MobileGame = 'Mobile Game',
  RPG = 'RPG',
  Shooter = 'Shooter',
  Rhythm = 'Rhythm',
  Platform = 'Platform',
  Mystery = 'Mystery',
  IndieGame = 'Indie Game',
  Party = 'Party',
  CardAndBoard = 'Card & Board'
}

export const videogamesGenreList = {
  ApexLegends: ["FPS", "Shooter", "Action", "Single & Multiplayer"],
  ClashRoyale: ["Card & Board", "RTS", "Mobile Game", "Strategy", "Multiplayer"],
  CSGO: ["FPS", "Shooter", "Action", "Multiplayer"],
  DeathByDaylight: ["Action", "Horror", "Strategy", "Survival", "Stealth", "Multiplayer"],
  Dota2: ["MOBA", "Action", "Strategy", "Multiplayer"],
  EscapeFromTarkov: ["Simulation", "FPS", "Shooter", "RPG", "MMO", "Action", "Single & Multiplayer"],
  FIFA22: ["Simulation", "Sports", "Action", "Single & Multiplayer"],
  Fortnite: ["Shooter", "Survival", "Action", "Open World", "Strategy", "Multiplayer"],
  FreeFire: ["Mobile Game", "Adventure", "Action", "Shooter", "Single & Multiplayer"],
  GTAV: ["Adventure", "FPS", "Shooter", "Action", "Open World", "Racing", "Single & Multiplayer"],
  LeagueOfLeyends: ["MOBA", "Action", "Multiplayer"],
  Minecraft: ["Simulation", "Adventure", "ARCADE", "MMO", "Survival", "Single & Multiplayer"],
  Overwatch: ["FPS", "Shooter", "Strategy", "Action", "Multiplayer"],
  PUBG_Battlegrounds: ["Shooter", "FPS", "Indie Game", "Action", "Adventure", "Multiplayer"],
  RainbowSixSiege: ["FPS", "Shooter", "Action", "Single & Multiplayer"],
  RocketLeague: ["Racing", "Action", "Sports", "Single & Multiplayer"],
  Rust: ["Adventure", "Shooter", "FPS", "RPG", "Action", "Single & Multiplayer"],
  SeaOfThieves: ["Adventure", "Action", "Open World", "Multiplayer"],
  VALORANT: ["Shooter", "FPS", "Action", "Multiplayer"],
  Warzone: ["FPS", "Shooter", "Action", "Multiplayer"],
  WorldOfWarcraft: ["RPG", "Adventure", "MMO", "Action", "Single & Multiplayer"],
}

export const videogames: Object = {
  ApexLegends: "Apex Legends",
  ClashRoyale: "Clash Royale",
  CSGO: "Counter-Strike: Global Offensive",
  DeathByDaylight: "Dead by Daylight",
  Dota2: "Dota 2",
  EscapeFromTarkov: "Escape from Tarkov",
  FIFA22: "FIFA 22",
  Fortnite: "Fortnite",
  FreeFire: "Garena Free Fire",
  GTAV: "Grand Theft Auto V",
  LeagueOfLeyends: "League of Legends",
  Minecraft: "Minecraft",
  Overwatch: "Overwatch",
  PUBG_Battlegrounds: "PUBG: BATTLEGROUNDS",
  RainbowSixSiege: "Tom Clancy's Rainbow Six Siege",
  RocketLeague: "Rocket League",
  Rust: "Rust",
  SeaOfThieves: "Sea of Thieves",
  VALORANT: "VALORANT",
  Warzone: "Call of Duty: Warzone",
  WorldOfWarcraft: "World of Warcraft",
}

export const videogamesFilenames: Object = {
  ApexLegends: "apexLegends_thumbnail.jpg",
  ClashRoyale: "clashRoyale_thumbnail.jpg",
  CSGO: "CSGO_thumbnail.jpg",
  DeathByDaylight: "deathByDaylight_thumbnail.jpg",
  Dota2: "dota2_thumbnail.jpg",
  EscapeFromTarkov: "escapeFromTarkov_thumbnail.jpg",
  FIFA22: "FIFA22_thumbnail.jpg",
  Fortnite: "fortnite_thumbnail.jpg",
  FreeFire: "freeFire_thumbnail.jpg",
  GTAV: "GTAV_thumbnail.jpg",
  LeagueOfLeyends: "LeagueOfLegends_thumbnail.jpg",
  Minecraft: "minecraft_thumbnail.jpg",
  Overwatch: "overwatch_thumbnail.jpg",
  PUBG_Battlegrounds: "pubg_thumbnail.jpg",
  RainbowSixSiege: "rainbows_thumbnail.jpg",
  RocketLeague: "rocketLeague_thumbnail.jpg",
  Rust: "rust_thumbnail.jpg",
  SeaOfThieves: "seaOfThieves_thumbnail.jpg",
  VALORANT: "valorant_thumbnail.jpg",
  Warzone: "warzone_thumbnail.jpg",
  WorldOfWarcraft: "worldOfWarcraft_thumbnail.jpg",
}