name: untitled_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  graphql_flutter: ^5.0.0
  flutter_bloc: ^7.3.3
  bloc: ^7.2.1
  flutter_secure_storage: ^5.0.0
  equatable: ^2.0.3
  photo_manager: ^2.0.7
  visibility_detector: ^0.2.2
  mime: ^1.0.1
  flutter_ffmpeg: ^0.4.2
  inview_notifier_list: ^2.0.0
  uuid: ^3.0.5
  cached_network_image: ^3.1.0+1
  scrollable_positioned_list: ^0.2.3
  video_player: 
  # ^2.2.13
    git: 
      url: https://github.com/juanmartin8a/video_player_2.1.10_custom
  path_provider: ^2.0.6
  path: ^1.8.0
  get: ^4.3.8
  video_trimmer:
    path: ./video_trimmer-0.5.4-custom/
  video_compress: 
    path: ./video_compress-3.0.0-custom/
  keyboard_attachable:
    path: ./keyboard_attachable-2.0.1-copy
  # better_player: ^0.0.72
  image_picker: ^0.8.5
  flutter_staggered_grid_view: ^0.4.1
  decorated_icon: ^1.2.1
  timeago: ^3.1.0
  video_thumbnail: ^0.4.3
  bubble_tab_indicator: ^0.1.6
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  # firebase_core: "^1.7.0"
  another_flushbar: ^1.10.28
  firebase_messaging: ^11.2.13
  flutter_local_notifications: ^9.1.1
  device_info_plus: ^3.1.1
  flutter_apns: ^1.5.1
  rich_text_controller: 
    git:
      url: https://github.com/micazi/rich_text_controller
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.0
  font_awesome_flutter: ^9.1.0
  fluentui_system_icons: ^1.1.161
  custom_refresh_indicator: ^1.1.1
  google_fonts: ^2.1.0
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  # flutter_native_image: ^0.0.6+1
  flutter_image_compress: ^1.1.0

dependency_overrides:
  platform: ^3.1.0
  gql_exec: ^0.3.0
  firebase_messaging: ^11.2.13
  video_player: # ^2.2.16
    git: 
      url: https://github.com/juanmartin8a/video_player_2.1.10_custom
  video_player_platform_interface:
    path: ./video_player_platform_interface-5.0.1_custom
  video_thumbnail: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.2.6-beta
  build_runner: '2.1.4'
  json_serializable: '6.0.1'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/clivy_isotype.png
    - assets/images/clivy_logo.png
    - assets/google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/google_fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
    - family: MPlus1
      fonts:
        - asset: assets/google_fonts/MPlus1/MPLUS1-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/MPlus1/MPLUS1-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/MPlus1/MPLUS1-Light.ttf
          weight: 300
        - asset: assets/google_fonts/MPlus1/MPLUS1-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/MPlus1/MPLUS1-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/MPlus1/MPLUS1-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/MPlus1/MPLUS1-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/MPlus1/MPLUS1-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/MPlus1/MPLUS1-Black.ttf
          weight: 900
    - family: Hind_Siliguri
      fonts:
        - asset: assets/google_fonts/Hind_Siliguri/HindSiliguri-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Hind_Siliguri/HindSiliguri-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Hind_Siliguri/HindSiliguri-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Hind_Siliguri/HindSiliguri-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Hind_Siliguri/HindSiliguri-Bold.ttf
          weight: 700
    - family: Hind
      fonts:
        - asset: assets/google_fonts/Hind/Hind-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Hind/Hind-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Hind/Hind-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Hind/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Hind/Hind-Bold.ttf
          weight: 700
    - family: Kumbh_Sans
      fonts:
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Kumbh_Sans/KumbhSans-Black.ttf
          weight: 900
    - family: Metropolis
      fonts:
        - asset: assets/google_fonts/Metropolis/Metropolis-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Metropolis/Metropolis-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Metropolis/Metropolis-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Metropolis/Metropolis-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Metropolis/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Metropolis/Metropolis-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Metropolis/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Metropolis/Metropolis-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Metropolis/Metropolis-Black.ttf
          weight: 900
    - family: Rubik
      fonts:
        # - asset: assets/google_fonts/Rubik/Metropolis-Thin.ttf
        #   weight: 100
        # - asset: assets/google_fonts/Rubik/Metropolis-ExtraLight.ttf
        #   weight: 200
        - asset: assets/google_fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: Libre_Franklin
      fonts:
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Libre_Franklin/LibreFranklin-Black.ttf
          weight: 900
    - family: MPlus2
      fonts:
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/MPLUS2/MPLUS2-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Light.ttf
          weight: 300
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/MPLUS2/MPLUS2-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/MPLUS2/MPLUS2-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/MPLUS2/MPLUS2-Black.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/google_fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Inter/Inter-Black.ttf
          weight: 900
    
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
